rails/config/routes.rb
Queristory::Application.routes.draw do
  resources :teams, only: [:index, :show]
  resources :queries
  post 'query/create' => 'queries#create'
  post 'page/create' => 'pages#create'
  get 'auth' => 'teams#auth'
  root 'queries#index'

end

rails/app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :query, touch: true
  validates :url, presence: true
end

rails/app/models/query.rb
class Query < ActiveRecord::Base
  has_many :pages
  belongs_to :team
  validates :q, presence: true
  default_scope -> { order('created_at DESC') }
  default_scope -> { where.not(q: nil) }

  def search_image?
    self.tbm == 'isch'
  end

  def identical_with?(query)
    self.q == query.q &&
    self.tbm == query.tbm &&
    self.queristory_from == query.queristory_from
  end
end

rails/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :queries
  validates :name, uniqueness: true
  has_secure_password

  def twitter_enabled?
    self.twitter_consumer_key &&
    self.twitter_consumer_secret &&
    self.twitter_oauth_key &&
    self.twitter_oauth_secret
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

end

rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def create
    team = Team.find_by(name: team_params[:team_name])
    if team && team.authenticate(team_params[:team_password])
      @page = Page.new(page_params)
      query_id = Query.find_by({
        q: @page.q,
        session_id: @page.session_id,
      }).id
      @page.update({query_id: query_id})

      if @page.save
        html = ( render partial: 'pages/page', locals: {page: @page} ).first

        WebsocketRails[team.name.to_sym].trigger 'page', { html: html, query_id: query_id}
        head :ok
      end
    end
  end

  private
    def page_params
      params.permit(:url, :title, :q, :rank, :start, :session_id)
    end

    def team_params
      params.permit(:team_name, :team_password)
    end
end

rails/app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    Rails.logger.level = Logger::ERROR
    queries_with_pages = Query.preload(:pages)
    @queries = queries_with_pages.page(params[:page]).per(25)
  end

  def create
    team = Team.find_by(name: team_params[:team_name])
    if team && team.authenticate(team_params[:team_password])
      @query = Query.new(query_with_team_id(team))
      if @query.save
        unless @query.identical_with?(Query.second)
          html = ( render partial: 'queries/query', locals: {query: @query} ).first
          WebsocketRails[team.name.to_sym].trigger 'query', html
          head :ok

          if team.twitter_enabled?
            tweet(format_for_tweet(@query), team)
          end
        else
          render nothing: true
        end
      else
        render nothing: true
      end
    end
  end

  private

    def query_params
      params.permit(:q, :oq, :tbm, :as_qdr, :lr, :tbs, :source, :safe, :num, :filter, :pws, :session_id, :queristory_from)
    end

    def team_params
      params.permit(:team_name, :team_password)
    end

    def query_with_team_id(team)
      query_hash = query_params.dup
      query_hash[:team_id] = team.id
      query_hash
    end

    def format_for_tweet(query)
      bitly = Bitly.new(ENV['bitly_legacy_login'], ENV['bitly_legacy_api_key'])
      url = "http://google.co.jp/search?q=#{query.q}&queristory_from=#{query.id}"
      url += '&tbm=isch' if query.search_image?
      tweet_content = "#{query.q.truncate(100)} #{bitly.shorten(url).short_url}"
      tweet_content += ' [画像検索]' if query.search_image?
      tweet_content
    end

    def tweet(tweet_content, team)
      require 'twitter'
      client = Twitter::REST::Client.new do |config|
        config.consumer_key       = team.twitter_consumer_key
        config.consumer_secret    = team.twitter_consumer_secret
        config.access_token        = team.twitter_oauth_key
        config.access_token_secret = team.twitter_oauth_secret
      end

      tweet_content = (tweet_content.length > 140) ? tweet_content[0..139].to_s : tweet_content

      begin
        client.update(tweet_content)
      rescue Exception => e
        p e
      end
    end
end

rails/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    render json: Team.pluck(:name)
  end

  def show
    if @team = Team.find_by(name: params[:id])
      @queries = @team.queries.page(params[:page]).per(25)
    else
      render nothing: true, status: 404
    end
  end

  def auth
    team = Team.find_by(name: team_params[:team_name])
    if team && team.authenticate(team_params[:team_password])
      render json: true
    else
      render json: false
    end
  end

  private
    def team_params
      params.permit(:team_name, :team_password)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  GOOGLE_SEARCH_URL = 'http://google.com/search'

  def url_for_search(query, option)
    url = "#{GOOGLE_SEARCH_URL}?q=#{query.q}"

    if option
      url += "&#{option}=#{query[option]}"
    end
    "#{url}&queristory_from=#{query.id}"
  end
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Queristory</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/app/views/pages/_page.html.erb
<% cache(page) do %>
  <span class='page_info sec_after'>
    <%= fa_icon 'clock-o' %>
    <%= "#{(page.created_at - page.query.created_at).round(1)} sec" %>
  </span>
  <span class='page_info rank'>
    <%= fa_icon 'trophy' %>
    <%= "#{(page.start.to_i + page.rank)}" %>
  </span>
  <%= link_to page.title, page.url %> <br>
<% end %>

rails/app/views/queries/_form.html.erb
<%= form_for(@query) do |f| %>
  <% if @query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query.errors.count, "error") %> prohibited this query from being saved:</h2>

      <ul>
      <% @query.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br>
    <%= f.text_area :query %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br>
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/queries/_query.html.erb
<% cache(query) do %>
  <div class='row query' id='item_<%= query.id %>'>
    <div class='columns column_date'>
      <p class='date'> <%= query.created_at.strftime('%Y/%m/%d') %> </p>
      <p class='time'> <%= query.created_at.strftime('%H:%M') %> </p>
    </div>
    <div class='columns column_left'>
      <p class='user_icon'><%= image_tag 'queristory.png' %></p>
    </div>
    <div class='columns column_right'>
      <h3 class='title'><span class='truncate'>
        <%= link_to query.q.truncate(80), url_for_search(query, nil) %>
      </span></h3>
      <div class='options'>
        <% ['tbm', 'as_qdr', 'lr', 'tbs', 'source', 'queristory_from'].each do |option| %>
          <% if query[option].present? %>
            <%= link_to url_for_search(query, option), class: option do %>
              <span class='label'>
                <%= "#{option}: #{query[option]}".truncate(25) %>
              </span>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class='content'>
        <% query.pages.each do |page| %>
          <%= render partial: 'pages/page', locals: {page: page} %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

rails/app/views/queries/edit.html.erb
<h1>Editing query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

rails/app/views/queries/index.html.erb
<div class='contents'>
  <a href='/'><h1>Queristory</h1></a>
  <% last_query_str = nil %>
  <div class='queries'>
    <% @queries.each do |query| %>
      <% unless last_query_str == query.q %>
        <%= render partial: 'queries/query', locals: {query: query} %>
      <% end %>
      <% last_query_str = query.q %>
    <% end %>
  <%= paginate @queries %>
  </div>
</div>

rails/app/views/queries/new.html.erb
<h1>New query</h1>

<%= render 'form' %>

<%= link_to 'Back', queries_path %>

rails/app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @query.query %>
</p>

<p>
  <strong>User:</strong>
  <%= @query.user_id %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @query.deleted_at %>
</p>

<%= link_to 'Edit', edit_query_path(@query) %> |
<%= link_to 'Back', queries_path %>